--DROP SCHEMA j2hrms;
--CREATE SCHEMA j2hrms;
--USE j2hrms;

CREATE TABLE IF NOT EXISTS role (
	id INT(11) NOT NULL AUTO_INCREMENT,
    code VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT code_uq UNIQUE KEY (code),
    CONSTRAINT name_uq UNIQUE KEY (name),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS employee (
	id int(11) NOT NULL AUTO_INCREMENT,
	last_name VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    middle_name VARCHAR(255) NOT NULL,
    extension_name VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user (
	id INT(11) NOT NULL AUTO_INCREMENT,
	employee_id INT(11) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT username_uq UNIQUE KEY (username),
    CONSTRAINT employee_uq UNIQUE KEY (employee_id),
    CONSTRAINT employee_fk FOREIGN KEY (employee_id) REFERENCES employee (id),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS user_role (
    id INT(11) NOT NULL AUTO_INCREMENT,
    user_id INT(11) NOT NULL,
    role_id INT(11) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_fk FOREIGN KEY (user_id) REFERENCES user (id),
    CONSTRAINT role_fk FOREIGN KEY (role_id) REFERENCES role (id),
    PRIMARY KEY (id)
);